background {
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 80
    position = 0, 200
    halign = center
    valign = center
}
